### ISSUE TITLE
How can I access template files in assets_vfsdata.go

### ISSUE THREAD

**Issue by weiofcn** [shurcooL/vfsgen#38]
Hi, @shurcooL , this is a great package and its quite handy. I met a problem and did some research and still can't figure out by myself because I am a newbie of golang. 

I have a file called `index.templ` which has already saved in `assets_vfsdata.go`, and there are also included many `js` and `css` files. 

`http.Handle("/", http.StripPrefix("/", fs))` uesed to satisfy my most requirements, but now I write some templates for my html pages, then I have no idea how to return a html page to http server after parsing my template and data.

It seems I have to retrieve the `compressedContent` in the map and replace it by using `template.New("").Parse()` before start http server.(this may not right)

So, is there a easier(or right) way to access partial template files and make them works like `template.ParseFiles("./index.templ")`. 

Thanks for the help.

**Comment by cryptix** [comment]
Have you seen [github.com/shurcooL/httpfs/html/vfstemplate](https://godoc.org/github.com/shurcooL/httpfs/html/vfstemplate)? It's like a drop-in replacement for `html/template` which works on `http.Filesystem`s. I think it should cover your needs.

**Comment by shurcooL** [comment]
@cryptix's suggestion is right on. Package [`github.com/shurcooL/httpfs/html/vfstemplate`](https://godoc.org/github.com/shurcooL/httpfs/html/vfstemplate) is a convenient existing solution for what you're looking, I recommend it.

Also, note that you shouldn't have to use anything unexported from _vfsdata files. The generated assets are exposed via the [`http.FileSystem`](https://github.com/shurcooL/vfsgen#usage) interface, and you should use its public method `Open` to access files. Files also implement [`GzipByter`](https://github.com/shurcooL/vfsgen#additional-embedded-information) interface for direct access to compressed bytes.

**Comment by weiofcn** [comment]
@cryptix @shurcooL Thanks, that's what I need.
