### ISSUE TITLE
Split files

### ISSUE THREAD

**Issue by ghostsquad** [shurcooL/vfsgen#41]
Do you know how I might split files? Given a single file, produce multiple cached output files?

**Comment by shurcooL** [comment]
Sorry, I don't understand what exactly you're asking. Can you clarify please?

**Comment by ghostsquad** [comment]
Of course. And I think I figured it out. Basically, for each file of a specific extension, I need to generate 2 additional files. I think that as I loop through directory contents (like here https://github.com/shurcooL/go/blob/master/gopherjs_http/vfs.go#L76), I can append extra files (with new extensions). Then when they are "opened" by vfsgen, I can reference the original file for its contents the perform the processing to create the new file.
