### ISSUE TITLE
How to serve gzipped bytes?

### ISSUE THREAD

**Issue by vearutop** [shurcooL/vfsgen#45]
I'm using `http.FileServer(assets)` to `ServeHTTP`, but that does not seem to use `gzip` compression. 

Is there an easy or supported way to leverage `GzipBytes() []byte` when serving?

**Comment by dmitshur** [comment]
Yes, there is. What you’re looking for is [`httpgzip.FileServer(assets, ...)`](https://godoc.org/github.com/shurcooL/httpgzip#FileServer)\.

[`httpgzip`](https://godoc.org/github.com/shurcooL/httpgzip) is a package that has a very similar API as `net/http`, except it’s aware of the [`GzipByter` interface](https://github.com/shurcooL/vfsgen#additional-embedded-information).

See its documentation at https://godoc.org/github.com/shurcooL/httpgzip.
