### ISSUE TITLE
Support Go modules.

### ISSUE THREAD

**Issue by Its-Alex** [shurcooL/vfsgen#59]
Hi, I want to know if vsfgen work with `go module`?

If no are you going to patch it ?

**Comment by dmitshur** [comment]
`vfsgen` itself supports modules.

`./cmd/vfsgendev`, a convenience tool for using `vfsgen` in a specific way, currently doesn't support modules because it looks for import paths only within GOPATH and GOROOT. However, there is an open PR #50 that adds support for modules.
