### ISSUE TITLE
Gzip Writer should use BestCompression

### ISSUE THREAD

**Issue by silverwind** [shurcooL/vfsgen#85]
Currently the gzip compression uses [`DefaultCompression`](https://golang.org/pkg/compress/gzip/#pkg-constants) which in most cases will evaluate to level `6`. Better compression can be achieved using [`BestCompression`](https://golang.org/pkg/compress/gzip/#pkg-constants) which is gzip level `9`. Compression level can be set using [`NewWriterLevel`](https://golang.org/pkg/compress/gzip/#NewWriterLevel) instead of [`NewWriter`](https://golang.org/pkg/compress/gzip/#NewWriter).

https://github.com/shurcooL/vfsgen/blob/92b8a710ab6cab4c09182a1fcf469157bc938f8f/generator.go#L173

**Comment by dmitshur** [comment]
This is a great catch. Thanks for spotting this opportunity and sending a PR.
